### PR TITLE
docs(architecture): draft the system architecture & user flow

### PR DESCRIPTION
**Pull request by vinhloc30796**
Closes WEB-237

### CODE REVIEW

**Comment by vinhloc30796** [comment]
nhờ a Trung @kenvinams review & comment nhé ạ

**Comment by kenvinams** [comment]
lgtm. 
Should also add a deadline and display time remaining till final group formation.
- The group formation is concluded until the deadline or can form pre-maturely? If yes, is it subject to change until the final group formation?
- How will the user receive the notification: through email or on web?

**Comment by loc-tread-labs** [comment]
> The group formation is concluded until the deadline or can form pre-maturely? If yes, is it subject to change until the final group formation?

current plan:

* with no deadline, user signs up for an account for the website (no deadline)
* by X deadline, user registers to join the event (Hoan Tat 2025), which will put them in the attendee pool
* after X, until Y deadline, user finishes providing their preference ranking out of the attendee pool
* after Y, until Z deadline, Creative Contact (system or team members) returns the group formation to the user

event starts after Z.

> How will the user receive the notification: through email or on web?

priority: email, then optionally web

**Comment by vinhloc30796** [comment]
merging this, if more comments then please PR @kenvinams @codingandcoffeerighthand @notHisu

**Pull request merged**
